// Regression gate for `rollback` (closes #262).
//
// Three defects in the same mechanism:
//
//  1. `secure --fix` runs harden-soul, which GENERATES SOUL.md. SOUL.md was
//     in no backup candidate list, so rollback left it on disk while
//     printing "All auto-fix changes have been reverted."
//  2. The v1 manifest wrote every backup candidate that happened to be
//     ABSENT at backup time into `createdFiles`, and rollback unlinked all
//     of them — so a `package.json` or `CLAUDE.md` the user wrote between
//     `--fix` and `rollback` was deleted as though HMA had generated it.
//  3. The SKILL-001 auto-fix appends an `opena2a-guard` signature block to
//     every unsigned skill file it finds. Those files were not backed up
//     either, so rollback could not restore them and said nothing about it.
//
// The contract now: restore what was backed up, delete a generated file only
// when its content hash still matches what HMA wrote, never delete anything
// it cannot prove it generated, and report all four outcomes.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { HardeningScanner } from '../../src/hardening/scanner';

const REPO_ROOT = join(__dirname, '..', '..');
const CLI = join(REPO_ROOT, 'dist', 'cli.js');

function canRunSpawn(): boolean {
  if (process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true') return false;
  return existsSync(CLI);
}

function sha256(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

/** Hand-build a backup dir so the rollback contract can be gated without a real scan. */
function seedBackup(dir: string, manifest: unknown, backedUp: Record<string, string> = {}): void {
  const backupDir = join(dir, '.hackmyagent-backup', '2026-07-27-120000');
  mkdirSync(backupDir, { recursive: true });
  for (const [rel, content] of Object.entries(backedUp)) {
    writeFileSync(join(backupDir, rel), content, 'utf8');
  }
  writeFileSync(join(backupDir, '.manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
}

describe('rollback contract (#262)', () => {
  let dir: string;
  let scanner: HardeningScanner;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'hma-262-'));
    scanner = new HardeningScanner();
  });

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  it('removes a generated file whose content still matches what was written', async () => {
    const generated = '# SOUL\n\nGenerated by harden-soul.\n';
    writeFileSync(join(dir, 'SOUL.md'), generated, 'utf8');
    seedBackup(dir, {
      version: 2,
      existingFiles: [],
      absentAtBackup: ['SOUL.md'],
      createdFiles: [{ path: 'SOUL.md', sha256: sha256(generated) }],
    });

    const report = await scanner.rollback(dir);

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(false);
    expect(report.removed).toEqual(['SOUL.md']);
    expect(report.keptModified).toEqual([]);
  });

  it('keeps a generated file the user edited, and says so', async () => {
    const generated = '# SOUL\n\nGenerated by harden-soul.\n';
    writeFileSync(join(dir, 'SOUL.md'), `${generated}\n## My own constraint\n`, 'utf8');
    seedBackup(dir, {
      version: 2,
      existingFiles: [],
      absentAtBackup: ['SOUL.md'],
      createdFiles: [{ path: 'SOUL.md', sha256: sha256(generated) }],
    });

    const report = await scanner.rollback(dir);

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(true);
    expect(readFileSync(join(dir, 'SOUL.md'), 'utf8')).toContain('My own constraint');
    expect(report.removed).toEqual([]);
    expect(report.keptModified).toEqual(['SOUL.md']);
  });

  it('restores a file that existed before the fix', async () => {
    const original = '{"mcpServers":{}}\n';
    writeFileSync(join(dir, 'mcp.json'), '{"mcpServers":{"tampered":true}}\n', 'utf8');
    seedBackup(
      dir,
      { version: 2, existingFiles: ['mcp.json'], absentAtBackup: [], createdFiles: [] },
      { 'mcp.json': original },
    );

    const report = await scanner.rollback(dir);

    expect(readFileSync(join(dir, 'mcp.json'), 'utf8')).toBe(original);
    expect(report.restored).toEqual(['mcp.json']);
  });

  it('never deletes a file a v1 manifest merely listed as absent', async () => {
    // The data-loss path: v1 wrote every absent candidate into createdFiles.
    // A package.json the user added after the fix must survive.
    const userFile = '{"name":"mine"}\n';
    writeFileSync(join(dir, 'package.json'), userFile, 'utf8');
    seedBackup(dir, {
      existingFiles: [],
      createdFiles: ['package.json', 'CLAUDE.md'],
    });

    const report = await scanner.rollback(dir);

    expect(existsSync(join(dir, 'package.json'))).toBe(true);
    expect(readFileSync(join(dir, 'package.json'), 'utf8')).toBe(userFile);
    // Reported, not silently left behind. CLAUDE.md never existed, so it is
    // not reported — there is nothing for the user to review.
    expect(report.keptUnverifiable).toEqual(['package.json']);
    expect(report.removed).toEqual([]);
  });

  it('does not delete a candidate that was never recorded as created', async () => {
    writeFileSync(join(dir, '.gitignore'), 'node_modules\n', 'utf8');
    seedBackup(dir, {
      version: 2,
      existingFiles: [],
      absentAtBackup: ['.gitignore'],
      createdFiles: [],
    });

    await scanner.rollback(dir);

    expect(existsSync(join(dir, '.gitignore'))).toBe(true);
  });

  it('does not escape the target directory via a manifest path', async () => {
    // The victim is a sibling of the scan target and is fully deletable by
    // this process, so a missing traversal guard fails the test for real
    // rather than being masked by a permission error.
    const parent = mkdtempSync(join(tmpdir(), 'hma-262-esc-'));
    const target = join(parent, 'scan-target');
    const victimDir = join(parent, 'sibling');
    mkdirSync(target, { recursive: true });
    mkdirSync(victimDir, { recursive: true });

    const content = 'do not delete me\n';
    const victim = join(victimDir, 'victim.md');
    writeFileSync(victim, content, 'utf8');

    try {
      seedBackup(target, {
        version: 2,
        existingFiles: [],
        absentAtBackup: [],
        // Resolves to ../sibling/victim.md — outside the scan target, and
        // the hash matches, so only the traversal guard stops the unlink.
        createdFiles: [{ path: '../sibling/victim.md', sha256: sha256(content) }],
      });

      const report = await scanner.rollback(target);

      expect(existsSync(victim)).toBe(true);
      expect(readFileSync(victim, 'utf8')).toBe(content);
      expect(report.removed).toEqual([]);
    } finally {
      rmSync(parent, { recursive: true, force: true });
    }
  });
});

describe('recordCreatedFiles gating (#262)', () => {
  let dir: string;
  let scanner: HardeningScanner;
  let backupDir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'hma-262-rec-'));
    scanner = new HardeningScanner();
    backupDir = join(dir, '.hackmyagent-backup', '2026-07-27-120000');
  });

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  function manifest(): any {
    return JSON.parse(readFileSync(join(backupDir, '.manifest.json'), 'utf8'));
  }

  it('records a candidate that was absent at backup time and exists now', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });
    const generated = '# SOUL\n';
    writeFileSync(join(dir, 'SOUL.md'), generated, 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    expect(manifest().createdFiles).toEqual([{ path: 'SOUL.md', sha256: sha256(generated) }]);
  });

  it('accepts an absolute candidate path (harden-soul returns one)', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });
    writeFileSync(join(dir, 'SOUL.md'), '# SOUL\n', 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, [join(dir, 'SOUL.md')]);

    expect(manifest().createdFiles.map((c: any) => c.path)).toEqual(['SOUL.md']);
  });

  it('refuses to record a file that existed at backup time', async () => {
    // A fix that MODIFIES a file must restore it, never delete it.
    seedBackup(dir, { version: 2, existingFiles: ['mcp.json'], absentAtBackup: [], createdFiles: [] });
    writeFileSync(join(dir, 'mcp.json'), '{}\n', 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, ['mcp.json']);

    expect(manifest().createdFiles).toEqual([]);
  });

  it('refuses to record a file that was in neither list', async () => {
    // The fix touched it, which is not proof the fix created it. Recording
    // it would let rollback delete a file the user wrote.
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: [], createdFiles: [] });
    writeFileSync(join(dir, 'SKILL.md'), '# skill\n', 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, ['SKILL.md']);

    expect(manifest().createdFiles).toEqual([]);
  });

  it('keeps the first hash when called twice (the one the user was told about)', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });
    const first = '# SOUL\n';
    writeFileSync(join(dir, 'SOUL.md'), first, 'utf8');
    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    writeFileSync(join(dir, 'SOUL.md'), '# SOUL\n\nlater edit\n', 'utf8');
    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    expect(manifest().createdFiles).toEqual([{ path: 'SOUL.md', sha256: sha256(first) }]);
  });

  it('records nothing when the candidate does not exist', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });

    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    expect(manifest().createdFiles).toEqual([]);
  });
});

describe('secure --fix then rollback, end to end (spawn, local-only)', { timeout: 240_000 }, () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'hma-262-e2e-'));
    // A password-bearing localhost URL rather than a vendor-prefixed key, so
    // the fixture cannot trip GitHub push protection.
    writeFileSync(join(dir, '.env'), 'DATABASE_URL=postgres://user:FAKEpassword@localhost:5432/db\n', 'utf8');
    writeFileSync(
      join(dir, 'mcp.json'),
      '{"mcpServers":{"fs":{"command":"npx","args":["-y","@modelcontextprotocol/server-filesystem","/"]}}}\n',
      'utf8',
    );
    // Present so the scan produces governance findings, which is what
    // triggers the harden-soul auto-fix that generates SOUL.md.
    writeFileSync(join(dir, 'SKILL.md'), '---\nname: demo\n---\n\n# Demo skill\n\nSummarize a file.\n', 'utf8');
  });

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  it.runIf(canRunSpawn())('leaves no generated SOUL.md behind and restores modified files', () => {
    const skillBefore = readFileSync(join(dir, 'SKILL.md'), 'utf8');
    const envBefore = readFileSync(join(dir, '.env'), 'utf8');

    const fix = spawnSync('node', [CLI, 'secure', dir, '--fix', '--ci'], {
      encoding: 'utf8',
      timeout: 180_000,
    });
    expect(fix.error).toBeUndefined();

    // Non-vacuity: the defect only exists when harden-soul actually generated
    // SOUL.md. If the fixture stops producing governance findings the
    // assertions below would pass for the wrong reason.
    expect(existsSync(join(dir, 'SOUL.md')), 'harden-soul did not generate SOUL.md — nothing to roll back').toBe(true);
    // And the SKILL-001 auto-fix must have modified the skill, which is the
    // second half of the contract (restore, not just delete).
    expect(readFileSync(join(dir, 'SKILL.md'), 'utf8')).not.toBe(skillBefore);

    const rollback = spawnSync('node', [CLI, 'rollback', dir], { encoding: 'utf8', timeout: 60_000 });
    expect(rollback.status).toBe(0);

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(false);
    expect(readFileSync(join(dir, 'SKILL.md'), 'utf8')).toBe(skillBefore);
    expect(readFileSync(join(dir, '.env'), 'utf8')).toBe(envBefore);

    // The claim the issue was filed against.
    expect(rollback.stdout || '').not.toMatch(/All auto-fix changes have been reverted/i);
  });

  it.runIf(canRunSpawn())('keeps a generated SOUL.md the user edited and names it', () => {
    spawnSync('node', [CLI, 'secure', dir, '--fix', '--ci'], { encoding: 'utf8', timeout: 180_000 });
    expect(existsSync(join(dir, 'SOUL.md')), 'harden-soul did not generate SOUL.md').toBe(true);

    writeFileSync(join(dir, 'SOUL.md'), `${readFileSync(join(dir, 'SOUL.md'), 'utf8')}\n## Mine\n`, 'utf8');

    const rollback = spawnSync('node', [CLI, 'rollback', dir], { encoding: 'utf8', timeout: 60_000 });
    const stdout = rollback.stdout || '';

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(true);
    expect(readFileSync(join(dir, 'SOUL.md'), 'utf8')).toContain('## Mine');
    expect(stdout).toMatch(/Kept 1 generated file/i);
    expect(stdout).toContain('SOUL.md');
    // No dead end: the user is told what to run.
    expect(stdout).toContain('rm SOUL.md');
  });
});
