// Regression gate for `rollback` (closes #262).
//
// Three defects in the same mechanism:
//
//  1. `secure --fix` runs harden-soul, which GENERATES SOUL.md. SOUL.md was
//     in no backup candidate list, so rollback left it on disk while
//     printing "All auto-fix changes have been reverted."
//  2. The v1 manifest wrote every backup candidate that happened to be
//     ABSENT at backup time into `createdFiles`, and rollback unlinked all
//     of them — so a `package.json` or `CLAUDE.md` the user wrote between
//     `--fix` and `rollback` was deleted as though HMA had generated it.
//  3. The SKILL-001 auto-fix appends an `opena2a-guard` signature block to
//     every unsigned skill file it finds. Those files were not backed up
//     either, so rollback could not restore them and said nothing about it.
//
// The contract now: restore what was backed up, delete a generated file only
// when its content hash still matches what HMA wrote, never delete anything
// it cannot prove it generated, and report all four outcomes.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { HardeningScanner } from '../../src/hardening/scanner';

const REPO_ROOT = join(__dirname, '..', '..');
const CLI = join(REPO_ROOT, 'dist', 'cli.js');

function canRunSpawn(): boolean {
  if (process.env.CI === 'true' || process.env.GITHUB_ACTIONS === 'true') return false;
  return existsSync(CLI);
}

function sha256(content: string): string {
  return createHash('sha256').update(content).digest('hex');
}

/** Hand-build a backup dir so the rollback contract can be gated without a real scan. */
function seedBackup(dir: string, manifest: unknown, backedUp: Record<string, string> = {}): void {
  const backupDir = join(dir, '.hackmyagent-backup', '2026-07-27-120000');
  mkdirSync(backupDir, { recursive: true });
  for (const [rel, content] of Object.entries(backedUp)) {
    writeFileSync(join(backupDir, rel), content, 'utf8');
  }
  writeFileSync(join(backupDir, '.manifest.json'), JSON.stringify(manifest, null, 2), 'utf8');
}

describe('rollback contract (#262)', () => {
  let dir: string;
  let scanner: HardeningScanner;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'hma-262-'));
    scanner = new HardeningScanner();
  });

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  it('removes a generated file whose content still matches what was written', async () => {
    const generated = '# SOUL\n\nGenerated by harden-soul.\n';
    writeFileSync(join(dir, 'SOUL.md'), generated, 'utf8');
    seedBackup(dir, {
      version: 2,
      existingFiles: [],
      absentAtBackup: ['SOUL.md'],
      createdFiles: [{ path: 'SOUL.md', sha256: sha256(generated) }],
    });

    const report = await scanner.rollback(dir);

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(false);
    expect(report.removed).toEqual(['SOUL.md']);
    expect(report.keptModified).toEqual([]);
  });

  it('keeps a generated file the user edited, and says so', async () => {
    const generated = '# SOUL\n\nGenerated by harden-soul.\n';
    writeFileSync(join(dir, 'SOUL.md'), `${generated}\n## My own constraint\n`, 'utf8');
    seedBackup(dir, {
      version: 2,
      existingFiles: [],
      absentAtBackup: ['SOUL.md'],
      createdFiles: [{ path: 'SOUL.md', sha256: sha256(generated) }],
    });

    const report = await scanner.rollback(dir);

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(true);
    expect(readFileSync(join(dir, 'SOUL.md'), 'utf8')).toContain('My own constraint');
    expect(report.removed).toEqual([]);
    expect(report.keptModified).toEqual(['SOUL.md']);
  });

  it('restores a file that existed before the fix', async () => {
    const original = '{"mcpServers":{}}\n';
    writeFileSync(join(dir, 'mcp.json'), '{"mcpServers":{"tampered":true}}\n', 'utf8');
    seedBackup(
      dir,
      { version: 2, existingFiles: ['mcp.json'], absentAtBackup: [], createdFiles: [] },
      { 'mcp.json': original },
    );

    const report = await scanner.rollback(dir);

    expect(readFileSync(join(dir, 'mcp.json'), 'utf8')).toBe(original);
    expect(report.restored).toEqual(['mcp.json']);
  });

  it('never deletes a file a v1 manifest merely listed as absent', async () => {
    // The data-loss path: v1 wrote every absent candidate into createdFiles.
    // A package.json the user added after the fix must survive.
    const userFile = '{"name":"mine"}\n';
    writeFileSync(join(dir, 'package.json'), userFile, 'utf8');
    seedBackup(dir, {
      existingFiles: [],
      createdFiles: ['package.json', 'CLAUDE.md'],
    });

    const report = await scanner.rollback(dir);

    expect(existsSync(join(dir, 'package.json'))).toBe(true);
    expect(readFileSync(join(dir, 'package.json'), 'utf8')).toBe(userFile);
    // Reported, not silently left behind. CLAUDE.md never existed, so it is
    // not reported — there is nothing for the user to review.
    expect(report.keptUnverifiable).toEqual(['package.json']);
    expect(report.removed).toEqual([]);
  });

  it('does not delete a candidate that was never recorded as created', async () => {
    writeFileSync(join(dir, '.gitignore'), 'node_modules\n', 'utf8');
    seedBackup(dir, {
      version: 2,
      existingFiles: [],
      absentAtBackup: ['.gitignore'],
      createdFiles: [],
    });

    await scanner.rollback(dir);

    expect(existsSync(join(dir, '.gitignore'))).toBe(true);
  });

  it('does not escape the target directory via a manifest path', async () => {
    // The victim is a sibling of the scan target and is fully deletable by
    // this process, so a missing traversal guard fails the test for real
    // rather than being masked by a permission error.
    const parent = mkdtempSync(join(tmpdir(), 'hma-262-esc-'));
    const target = join(parent, 'scan-target');
    const victimDir = join(parent, 'sibling');
    mkdirSync(target, { recursive: true });
    mkdirSync(victimDir, { recursive: true });

    const content = 'do not delete me\n';
    const victim = join(victimDir, 'victim.md');
    writeFileSync(victim, content, 'utf8');

    try {
      seedBackup(target, {
        version: 2,
        existingFiles: [],
        absentAtBackup: [],
        // Resolves to ../sibling/victim.md — outside the scan target, and
        // the hash matches, so only the traversal guard stops the unlink.
        createdFiles: [{ path: '../sibling/victim.md', sha256: sha256(content) }],
      });

      const report = await scanner.rollback(target);

      expect(existsSync(victim)).toBe(true);
      expect(readFileSync(victim, 'utf8')).toBe(content);
      expect(report.removed).toEqual([]);
    } finally {
      rmSync(parent, { recursive: true, force: true });
    }
  });

  it('does not report on out-of-tree paths from a v1 manifest', async () => {
    // The legacy loop performs no write, which is why it had no containment
    // check — but an unguarded path still let a forged manifest probe for files
    // outside the tree and have their existence reported back. The guard was
    // added in this branch alongside #312 and had no failing case, so it was
    // enforcement nobody could fail.
    const parent = mkdtempSync(join(tmpdir(), 'hma-312-legacy-'));
    const target = join(parent, 'scan-target');
    const victimDir = join(parent, 'sibling');
    mkdirSync(target, { recursive: true });
    mkdirSync(victimDir, { recursive: true });
    writeFileSync(join(victimDir, 'private.txt'), 'exists\n', 'utf8');
    // In tree, so the loop is proven to still work.
    writeFileSync(join(target, 'CLAUDE.md'), 'exists\n', 'utf8');

    try {
      seedBackup(target, {
        version: 1,
        existingFiles: [],
        absentAtBackup: [],
        createdFiles: ['../sibling/private.txt', 'CLAUDE.md'],
      });

      const report = await scanner.rollback(target);

      expect(
        report.keptUnverifiable,
        'a v1 manifest probed for a file outside the scanned tree and the report '
        + 'confirmed it exists',
      ).not.toContain('../sibling/private.txt');
      // Non-vacuity: the in-tree entry must still be reported, or the guard has
      // simply disabled the loop.
      expect(report.keptUnverifiable).toContain('CLAUDE.md');
      expect(existsSync(join(victimDir, 'private.txt'))).toBe(true);
    } finally {
      rmSync(parent, { recursive: true, force: true });
    }
  });

  it('refuses an implausibly large manifest instead of reading it whole', async () => {
    // The #305 follow-up bounded the manifest read on the SCAN path and
    // exempted this one, reasoning that "rollback only ever reads a manifest
    // HMA itself just wrote". #312 disproved that: the same cloned tree that
    // supplies the traversal paths supplies this file, and a stamp of
    // `9999-…` is always the one selected. Measured before the guard: a 60MB
    // manifest read whole, 493MB resident.
    //
    // Fails CLOSED — an oversized manifest takes the existing unreadable
    // branch, which names the directory to restore from by hand, so refusing
    // is not a dead end.
    const backupDir = join(dir, '.hackmyagent-backup', '2026-07-27-120000');
    mkdirSync(backupDir, { recursive: true });
    const oversized = JSON.stringify({
      version: 2,
      existingFiles: [],
      absentAtBackup: [],
      createdFiles: [],
      pad: 'A'.repeat(11 * 1024 * 1024),
    });
    writeFileSync(join(backupDir, '.manifest.json'), oversized, 'utf8');

    await expect(scanner.rollback(dir)).rejects.toThrow(/unreadable/i);

    // Non-vacuity: the same fixture UNDER the bound must still roll back, or
    // this only proves rollback can throw.
    writeFileSync(
      join(backupDir, '.manifest.json'),
      JSON.stringify({ version: 2, existingFiles: [], absentAtBackup: [], createdFiles: [] }),
      'utf8',
    );
    await expect(scanner.rollback(dir)).resolves.toBeTruthy();
  });

  /**
   * #312 — the same traversal, through the loop that had no guard.
   *
   * `createdFiles` was guarded (the test above); `existingFiles` was not, and it
   * is the loop that WRITES. The manifest is read from the scanned tree, so a
   * cloned repo carrying its own `.hackmyagent-backup/9999-99-99-999999/` — a
   * stamp that sorts above any real one, and is therefore always selected as
   * the latest — turned `rollback` into an arbitrary file write that reported
   * success.
   *
   * Pre-existing: reproduces on 0.25.1 too, so not a regression from this
   * stack. It is #305 that taught this code to reason about forged manifests in
   * an attacker-controlled tree while leaving the manifest a write primitive.
   *
   * #323 — this fixture uses only a `../` traversal, and it PASSED against the
   * symlink-vulnerable restore loop (#318): a lexical containment check on the
   * joined destination decides where the string points, not where the filesystem
   * sends it. The symlink cases for both ends, and for the unlink loop, live in
   * `backup-identity.test.ts`. Keep this one — the lexical guard is still
   * load-bearing, and it is what stops a traversal before any syscall is spent.
   */
  it('does not WRITE outside the target directory via a manifest path', async () => {
    const parent = mkdtempSync(join(tmpdir(), 'hma-312-'));
    const target = join(parent, 'scan-target');
    mkdirSync(target, { recursive: true });

    // `seedBackup` stamps the backup `2026-07-27-120000`, and the escape is
    // built around that name so BOTH ends resolve somewhere real:
    //   source = join(backupDir, ESCAPE) -> <backupDir>/authorized_keys
    //   dest   = join(target,    ESCAPE) -> <parent>/2026-07-27-120000/…
    // The source has to exist, or a missing containment guard fails on ENOENT
    // instead of writing, and the test would pass for the wrong reason.
    const STAMP = '2026-07-27-120000';
    const ESCAPE = `../${STAMP}/authorized_keys`;
    const victimDir = join(parent, STAMP);
    mkdirSync(victimDir, { recursive: true });

    const original = 'LEGITIMATE_USER_CONTENT\n';
    const victim = join(victimDir, 'authorized_keys');
    writeFileSync(victim, original, 'utf8');

    try {
      seedBackup(
        target,
        {
          version: 2,
          existingFiles: [ESCAPE, 'config.json'],
          absentAtBackup: [],
          createdFiles: [],
        },
        { 'config.json': 'RESTORED_ORIGINAL\n', 'authorized_keys': 'ATTACKER_PAYLOAD\n' },
      );
      writeFileSync(join(target, 'config.json'), 'MODIFIED\n', 'utf8');

      // Precondition: the escape must actually resolve to the victim, or this
      // asserts nothing. A broken traversal path exits the same way a blocked
      // one does.
      expect(join(target, ESCAPE)).toBe(victim);
      expect(existsSync(join(target, '.hackmyagent-backup', STAMP, 'authorized_keys'))).toBe(true);

      const report = await scanner.rollback(target);

      expect(
        readFileSync(victim, 'utf8'),
        'rollback overwrote a file outside the scanned tree from a forged manifest, '
        + 'and reported a clean restore (#312)',
      ).toBe(original);
      expect(report.restored).not.toContain(ESCAPE);

      // Non-vacuity: the guard must block the escape without becoming a blanket
      // refusal. An in-tree entry in the SAME manifest still has to restore, or
      // this passes just as well against a rollback that does nothing at all.
      expect(
        readFileSync(join(target, 'config.json'), 'utf8'),
        'the legitimate in-tree restore was blocked too; the guard is too broad',
      ).toBe('RESTORED_ORIGINAL\n');
      expect(report.restored).toContain('config.json');
    } finally {
      rmSync(parent, { recursive: true, force: true });
    }
  });
});

describe('recordCreatedFiles gating (#262)', () => {
  let dir: string;
  let scanner: HardeningScanner;
  let backupDir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'hma-262-rec-'));
    scanner = new HardeningScanner();
    backupDir = join(dir, '.hackmyagent-backup', '2026-07-27-120000');
  });

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  function manifest(): any {
    return JSON.parse(readFileSync(join(backupDir, '.manifest.json'), 'utf8'));
  }

  it('records a candidate that was absent at backup time and exists now', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });
    const generated = '# SOUL\n';
    writeFileSync(join(dir, 'SOUL.md'), generated, 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    expect(manifest().createdFiles).toEqual([{ path: 'SOUL.md', sha256: sha256(generated) }]);
  });

  it('accepts an absolute candidate path (harden-soul returns one)', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });
    writeFileSync(join(dir, 'SOUL.md'), '# SOUL\n', 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, [join(dir, 'SOUL.md')]);

    expect(manifest().createdFiles.map((c: any) => c.path)).toEqual(['SOUL.md']);
  });

  it('refuses to record a file that existed at backup time', async () => {
    // A fix that MODIFIES a file must restore it, never delete it.
    seedBackup(dir, { version: 2, existingFiles: ['mcp.json'], absentAtBackup: [], createdFiles: [] });
    writeFileSync(join(dir, 'mcp.json'), '{}\n', 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, ['mcp.json']);

    expect(manifest().createdFiles).toEqual([]);
  });

  it('refuses to record a file that was in neither list', async () => {
    // The fix touched it, which is not proof the fix created it. Recording
    // it would let rollback delete a file the user wrote.
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: [], createdFiles: [] });
    writeFileSync(join(dir, 'SKILL.md'), '# skill\n', 'utf8');

    await scanner.recordCreatedFiles(dir, backupDir, ['SKILL.md']);

    expect(manifest().createdFiles).toEqual([]);
  });

  it('keeps the first hash when called twice (the one the user was told about)', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });
    const first = '# SOUL\n';
    writeFileSync(join(dir, 'SOUL.md'), first, 'utf8');
    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    writeFileSync(join(dir, 'SOUL.md'), '# SOUL\n\nlater edit\n', 'utf8');
    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    expect(manifest().createdFiles).toEqual([{ path: 'SOUL.md', sha256: sha256(first) }]);
  });

  it('records nothing when the candidate does not exist', async () => {
    seedBackup(dir, { version: 2, existingFiles: [], absentAtBackup: ['SOUL.md'], createdFiles: [] });

    await scanner.recordCreatedFiles(dir, backupDir, ['SOUL.md']);

    expect(manifest().createdFiles).toEqual([]);
  });
});

describe('secure --fix then rollback, end to end (spawn, local-only)', { timeout: 240_000 }, () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'hma-262-e2e-'));
    // A password-bearing localhost URL rather than a vendor-prefixed key, so
    // the fixture cannot trip GitHub push protection.
    writeFileSync(join(dir, '.env'), 'DATABASE_URL=postgres://user:FAKEpassword@localhost:5432/db\n', 'utf8');
    writeFileSync(
      join(dir, 'mcp.json'),
      '{"mcpServers":{"fs":{"command":"npx","args":["-y","@modelcontextprotocol/server-filesystem","/"]}}}\n',
      'utf8',
    );
    // Present so the scan produces governance findings, which is what
    // triggers the harden-soul auto-fix that generates SOUL.md.
    writeFileSync(join(dir, 'SKILL.md'), '---\nname: demo\n---\n\n# Demo skill\n\nSummarize a file.\n', 'utf8');
  });

  afterEach(() => {
    if (dir) rmSync(dir, { recursive: true, force: true });
  });

  it.runIf(canRunSpawn())('leaves no generated SOUL.md behind and restores modified files', () => {
    const skillBefore = readFileSync(join(dir, 'SKILL.md'), 'utf8');
    const envBefore = readFileSync(join(dir, '.env'), 'utf8');

    const fix = spawnSync('node', [CLI, 'secure', dir, '--fix', '--ci'], {
      encoding: 'utf8',
      timeout: 180_000,
    });
    expect(fix.error).toBeUndefined();

    // Non-vacuity: the defect only exists when harden-soul actually generated
    // SOUL.md. If the fixture stops producing governance findings the
    // assertions below would pass for the wrong reason.
    expect(existsSync(join(dir, 'SOUL.md')), 'harden-soul did not generate SOUL.md — nothing to roll back').toBe(true);
    // And the SKILL-001 auto-fix must have modified the skill, which is the
    // second half of the contract (restore, not just delete).
    expect(readFileSync(join(dir, 'SKILL.md'), 'utf8')).not.toBe(skillBefore);

    const rollback = spawnSync('node', [CLI, 'rollback', dir], { encoding: 'utf8', timeout: 60_000 });
    expect(rollback.status).toBe(0);

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(false);
    expect(readFileSync(join(dir, 'SKILL.md'), 'utf8')).toBe(skillBefore);
    expect(readFileSync(join(dir, '.env'), 'utf8')).toBe(envBefore);

    // The claim the issue was filed against.
    expect(rollback.stdout || '').not.toMatch(/All auto-fix changes have been reverted/i);
  });

  it.runIf(canRunSpawn())('keeps a generated SOUL.md the user edited and names it', () => {
    spawnSync('node', [CLI, 'secure', dir, '--fix', '--ci'], { encoding: 'utf8', timeout: 180_000 });
    expect(existsSync(join(dir, 'SOUL.md')), 'harden-soul did not generate SOUL.md').toBe(true);

    writeFileSync(join(dir, 'SOUL.md'), `${readFileSync(join(dir, 'SOUL.md'), 'utf8')}\n## Mine\n`, 'utf8');

    const rollback = spawnSync('node', [CLI, 'rollback', dir], { encoding: 'utf8', timeout: 60_000 });
    const stdout = rollback.stdout || '';

    expect(existsSync(join(dir, 'SOUL.md'))).toBe(true);
    expect(readFileSync(join(dir, 'SOUL.md'), 'utf8')).toContain('## Mine');
    expect(stdout).toMatch(/Kept 1 generated file/i);
    expect(stdout).toContain('SOUL.md');
    // No dead end: the user is told what to run.
    expect(stdout).toContain('rm SOUL.md');
  });
});
